### ISSUE TITLE
bug: calling .setCommands(bot) on commands containing UpperCase letters or symbols will throw

### ISSUE THREAD

**Issue by carafelix** [grammyjs/commands#24]
Even if RegExp commands are not meant to be used / listed in the commands menu, a more appropriate error should be shown. Noted that if an error handler is not registered, it will stop execution

In my opinion it should be ok to show regexp commands in the commands menu, even if they are not meant to be used in their string representation. It should not be a problem since their names are already being registered as strings

```ts
myCommands.command(/delete_(.*)/, 'el otro', async (c) => {
   await c.reply('papito')
})

await myCommands.setCommands(bot)
```
will throw:
```bash
error: Uncaught (in promise) GrammyError: Call to 'setMyCommands' failed! (400: Bad Request: BOT_COMMAND_INVALID)
    return new GrammyError(
           ^
    at toGrammyError (https://deno.land/x/grammy@v1.22.4/core/error.ts:43:12)
    at ApiClient.callApi (https://deno.land/x/grammy@v1.22.4/core/client.ts:328:20)
    at eventLoopTick (ext:core/01_core.js:168:7)
    at async Promise.all (index 0)
    at async Commands.setCommands (file:///media/martincito/freedom/repos/grammy/commands/src/commands.ts:197:9)
    at async file:///media/martincito/freedom/repos/grammy/testbot-deno/src/bot.ts:62:1
```

Even a regex-like-string will throw:
```ts
userCommands.command('/delete/', 'el otro', async (c) => {
   await c.reply('papito')
})
```

**Comment by carafelix** [comment]
> I thought we handled / filtered these on another PQ 🤔

That one was for `SetMyCommands`. `SetCommands` depends uses `.toArgs` instead of `.toSingleScopeArgs` (the one that was modified). I didn't modified that, but now you said that, I remembered, it should be as easy as adding the same filter to `.toArgs`

**Comment by roziscoding** [comment]
> Also, [telegram API](https://core.telegram.org/method/bots.setBotCommands) does not specify which is and which is not allowed

It actually [does](https://core.telegram.org/bots/api#getuserchatboosts).
We can just clean the strings up with `.replace(/[^_\w]/g, "").toLowerCase()`

**Comment by carafelix** [comment]
> We can just clean the strings up with .replace(/[^_\w]/g, "").toLowerCase()

In that case the command shown in the commands menu would not match the actual command that is registered, and will not trigger it either.

for ex: 
A command registered under the `/pApi` name, would match solely under user input `/pApi`, but if at `setCommands`-time  we lowercase them, the command menu will show `/papi`. the `/pApi` handler will not be trigger if you click/input `/papi` 

I think it's okay to thrown on UpperCases commands, they should be supported by the handlers but discourage from usage. Filtering them at `setCommands` time would lead to a Silent Error

**Comment by carafelix** [comment]
I added a note into the docs draft:
https://github.com/grammyjs/website/blob/fb7ee75f417648ecf3e619141d4b951ed51e0046/site/docs/plugins/commands.md?plain=1#L172-L180
should be enough?
