### ISSUE TITLE
Case-insensitive command names

### ISSUE THREAD

**Issue by rojvv** [grammyjs/commands#27]
I think there should be an option to make command names case-insensitive, or do it by default.

## Use Case

There are many use cases for this, and here's an example. Imagine we have a bot that configures PC builds, and includes a footer like this in one of its messages:

> See /available_CPUs.

This cannot be handled if the command name passed to the filter doesn't look like the one in the message. And once it's handled the way it is displayed to the user, it can't be handled when the cases are changed, say all lower like `/available_cpus`.

It is case-insensitive by default in most of the other bot frameworks.

**Comment by KnorpelSenf** [comment]
I think it makes a lot of sense for the commands plugin to support this in some way or another. That would also allow the core library to stay lean and not add too many options. There has been little demand for this, but in my personal view, the commands plugin is the right place for supporting every edge case. What do you think?

**Comment by roziscoding** [comment]
Honestly, I thought we already supported this 😅
This makes total sense. I'll PQ in a few hours.

**Comment by KnorpelSenf** [comment]
> Honestly, I thought we already supported this 😅

I honestly was not sure about that, either lol

**Comment by roziscoding** [comment]
> I'll PQ in a few hours.

So... "few" is a very subject measure okay? 😅
