### ISSUE TITLE
Support for Exporting and Importing Commands

### ISSUE THREAD

**Issue by nicetomytyuk** [grammyjs/commands#38]
It would be cool if the plugin supported exporting and importing commands. This feature would enhance the modularity and reusability of command definitions, making it easier to manage and maintain large bot projects.

Something like this:

**1. Exporting a `Command`:**

```ts
import { Command } from "@grammyjs/commands";

const startCommand = new Command("start", "Initializes bot configuration")
    .addToScope(
        { type: "all_group_chats" },
        (ctx) => ctx.reply(`Hello, members of ${ctx.chat.title}!`),
    );

export default startCommand;
```

**2. Importing a `Command`**

```ts
import { Bot } from "grammy";
import { Commands } from "@grammyjs/commands";
import startCommand from "./commands/start.js";

const bot = new Bot("<telegram token>");

const myCommands = new Commands();

myCommands.define(startCommand);

// Calls `setMyCommands`
await myCommands.setCommands(bot);

// Registers the command handlers
bot.use(myCommands);

bot.start();
```

*Here maybe the `.define` could support both single `Command` or an array of `Command` (?)

### Benefits:

- **Modularity**: Commands can be organized in separate files, making the project structure cleaner and easier to manage.
- **Reusability**: Common commands can be reused across different projects by simply importing them.
- **Maintainability**: Changes to a specific command can be made in its dedicated file, reducing the risk of conflicts and making the codebase easier to maintain.

**Comment by carafelix** [comment]
I have a local working branch, I'll pr maybe in the weekend

**Comment by carafelix** [comment]
marked as completed from merging #51
