### ISSUE TITLE
How to get command parameter

### ISSUE THREAD

**Issue by polRk** [grammyjs/commands#58]
example: `/echo Cow`, how to get Cow?

**Comment by KnorpelSenf** [comment]
This is not released yet, but you can try out the changes in #57 and give feedback on whether they work. Then they can be merged faster and the feature can be released sooner.

**Comment by roziscoding** [comment]
If you want to do it manually or don't want to use that branch, you can get the message test (for example `ctx.msg.text`) and implement your logic to extract the parameter
